# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPublish
  jobs:
  - job: 'Build'
    steps:
    - task: Maven@3
      name: 'Build'
      displayName: 'Build'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-DskipTests -Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        goals: 'clean install'
  - job: 'PublishArtifact'
    pool: server
    dependsOn: 'Build'
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'nitinp2mad'
        method: 'POST'
        body: |
          {
            "artifacts":[
                {
                  "name":"sp-boot-app",
                  "version":"1.$(build.buildId)",
                  "semanticVersion":"1.$(build.buildId).0",
                  "repositoryName":"sp-boot-repo"
                }
            ],
            "pipelineName":"$(system.teamProject)/$(build.definitionName)",
            "taskExecutionNumber":"$(build.buildId)",
            "stageName":"$(system.jobDisplayName)",
            "branchName": "$(build.sourceBranchName)"
          }
        urlSuffix: '/artifact/registration?orchestrationToolId=8805a136dbfad810c93442c505961929'
        waitForCompletion: 'false'

- stage: TestAndPackage
  dependsOn: 'BuildAndPublish'
  jobs:          
  - job: 'Test'
    steps:
    - task: Maven@3
      name: 'Test'
      displayName: 'Test'
      inputs:
        goals: 'test'
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/target/surefire-reports/*.xml'
        testRunTitle: 'Test'
  - job: 'Package'
    pool: server
    dependsOn: 'Test'
    steps:
      - task: InvokeRESTAPI@1
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: 'nitinp2mad'
          method: 'POST'
          body: |
            {
              "name": "sp-package",
              "artifacts":[ 
                  {"name":"sp-boot-app",
                  "version":"1.$(build.buildId)", 
                  "repositoryName":"sp-boot-repo" 
                  }
              ],
              "pipelineName": "$(system.teamProject)/$(build.definitionName)",
              "taskExecutionNumber": "$(build.buildId)",
              "stageName": "$(system.jobDisplayName)",
              "branchName": "$(build.sourceBranchName)"
            }
          urlSuffix: '/package/registration?orchestrationToolId=8805a136dbfad810c93442c505961929'
          waitForCompletion: 'false'

- stage: Deploy
  dependsOn: 'TestAndPackage'
  jobs:
  - job: 'Deploy'
    # pool : serve
    steps:
    - script: echo Deploying the code!