# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: server
#  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        Phase: 'STARTED'
    - script: mvn clean install
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        Phase: 'COMPLETED'
- stage: Test
  jobs:
  - job: Test
    steps:
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        UpstreamJob: 'Build'
        Phase: 'STARTED'
    - script: echo Testing on Windows!
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        UpstreamJob: 'Build'
        Phase: 'COMPLETED'
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        UpstreamJob: 'Test'
        Phase: 'STARTED'
    - script: echo Deploying the code!
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        UpstreamJob: 'Test'
        Phase: 'COMPLETED'

