# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'Build'
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        Phase: 'STARTED'
    - script: mvn clean install
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        Phase: 'COMPLETED'
  - job: 'Test'
    dependsOn: 'Build'
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
       connectedServiceName: 'nitinp2mad2'
       upstream: 'Build'
       Phase: 'STARTED'
    - script: echo Testing on Windows!
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        upstream: 'Build'
        Phase: 'COMPLETED'
  - job: 'Deploy'
    pool : server
    dependsOn: 'Test'
    steps:
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        UpstreamJob: 'Test'
        Phase: 'STARTED'
    # - script: echo Deploying the code!
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        UpstreamJob: 'Test'
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'nitinp2mad2'
        UpstreamJob: 'Test'
        Phase: 'COMPLETED'

