# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'Build'
    steps:
    - task: Maven@3
      name: 'Build'
      displayName: 'Build'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-DskipTests -Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        goals: 'clean install'
  - job: 'Test'
    dependsOn: 'Build'
    steps:
    - task: Maven@3
      name: 'Test'
      displayName: 'Test'
      inputs:
        goals: 'test'
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/target/surefire-reports/*.xml'
        testRunTitle: 'Test'
  - job: 'Deploy'
    pool : server
    dependsOn: 'Test'
    steps:
    - script: echo Deploying the code!
 
